### ISSUE TITLE
GetMessage timeout/delay isn't working

### ISSUE THREAD

**Issue by DemonMartin** [Sadzurami/node-kopeechka-store#2]
Hello, currently as I try, the timeout/delay doesn't seem to work. 
Based on my testing on Line 121 in dist/Kopeechka.js that is executed before the time actually stopped. If I switch places by recoding the code, so instead it checks "if res.message is not WAIT LINK return res" the getMessage function thinks that this.waitMessage has returned some value even tho it hasn't.

Something weird is going on, could you check if thats only me?

**Comment by Sadzurami** [comment]
@DemonMartin Hello, it looks like a bug. But I don't have time for it right now. Maybe later.
PR is welcome.

**Comment by lxntagram** [comment]
still not working
